### ISSUE TITLE
redirect loop on user delete

### ISSUE THREAD

**Issue by solace** [arckinteractive/deleted_user_content#1]
Hi,

I have a client running Elgg 1.8.17 and (previously) Deleted User Content 1.0.

On user delete, I am observing a redirect loop on the endpoint: `/admin/user/delete/content_policy?guid=XXXX` which is related to this plugin.

The current `.htaccess` matches the `htaccess_dist` barring increases to `memory_limit`, `post_max_size` and `upload_max_filesize`.

I have since updated to Deleted User Content 1.0.1 for Elgg 1.8, upgraded and cleared the cache, but the issue still persists.

Do you have any recommendations for resolving this issue?

Thanks

**Comment by beck24** [comment]
I haven't experienced this on any of our sites, I'll keep an eye open.  Unless you're a developer I don't have any recommendations.  If you are I would say throw in some error logs to see why it's getting redirected.  I haven't looked at this code recently but I believe it's looking for a specific set of conditions on the action hook.
Have you ruled out interference from other plugins?

**Comment by solace** [comment]
I am a dev.

Am awaiting information from their sysadmin regarding their logs. But will try disabling other plugins to eliminate that as a factor in the interim.

Thanks for the suggestions.

**Comment by solace** [comment]
Hi @beck24, another plugin which uses the action hook needed to be positioned after the `deleted_user_content` plugin.  This problem is resolved.

Thanks for the tip!
